// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGJZ_EcXsoAtMvZGK9M_3GTeBDg0DsTs',
    appId: '1:955155540531:web:4f75336a9e8e5b33535146',
    messagingSenderId: '955155540531',
    projectId: 'carrot-17375',
    authDomain: 'carrot-17375.firebaseapp.com',
    storageBucket: 'carrot-17375.firebasestorage.app',
    measurementId: 'G-GSSBWJJCDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1F9YBWUuovh4ZXD-e_jWGkDqvYBZkRwg',
    appId: '1:955155540531:android:de8aac377ccba7c3535146',
    messagingSenderId: '955155540531',
    projectId: 'carrot-17375',
    storageBucket: 'carrot-17375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AKAA8DYBbFyKyY6CqlnVsRjK7gt_Y1A',
    appId: '1:955155540531:ios:76aef80d4b773c71535146',
    messagingSenderId: '955155540531',
    projectId: 'carrot-17375',
    storageBucket: 'carrot-17375.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_AKAA8DYBbFyKyY6CqlnVsRjK7gt_Y1A',
    appId: '1:955155540531:ios:76aef80d4b773c71535146',
    messagingSenderId: '955155540531',
    projectId: 'carrot-17375',
    storageBucket: 'carrot-17375.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvGJZ_EcXsoAtMvZGK9M_3GTeBDg0DsTs',
    appId: '1:955155540531:web:19c0660d245afdc4535146',
    messagingSenderId: '955155540531',
    projectId: 'carrot-17375',
    authDomain: 'carrot-17375.firebaseapp.com',
    storageBucket: 'carrot-17375.firebasestorage.app',
    measurementId: 'G-HEBR8YFSWG',
  );
}
